from typing import Dict, Any

CARD_DB: Dict[str, Dict[str, Any]] = {
    "Knight":           {"elixir": 3, "roles": ["support","defense"], "tags": ["ground_dps"]},
    "Archers":          {"elixir": 3, "roles": ["support","defense"], "tags": ["anti_air","ranged"]},
    "Goblins":          {"elixir": 2, "roles": ["support","defense"], "tags": ["ground_dps","swarm"]},
    "Giant":            {"elixir": 5, "roles": ["offense","wincon"], "tags": ["wincon"]},
    "P.E.K.K.A":        {"elixir": 7, "roles": ["support","defense"], "tags": ["tank_killer","ground_dps"]},
    "Minions":          {"elixir": 3, "roles": ["support","defense"], "tags": ["anti_air","air_attacker","swarm"]},
    "Balloon":          {"elixir": 5, "roles": ["offense","wincon"], "tags": ["wincon","air_attacker"]},
    "Witch":            {"elixir": 5, "roles": ["support","defense"], "tags": ["splash","spawner"]},
    "Barbarians":       {"elixir": 5, "roles": ["defense"],             "tags": ["ground_dps","swarm"]},
    "Golem":            {"elixir": 8, "roles": ["offense","wincon"], "tags": ["wincon"]},
    "Skeletons":        {"elixir": 1, "roles": ["cycle","defense"],  "tags": ["swarm","cycle"]},
    "Valkyrie":         {"elixir": 4, "roles": ["support","defense"], "tags": ["splash","ground_dps"]},
    "Skeleton Army":    {"elixir": 3, "roles": ["defense"],             "tags": ["swarm","ground_dps"]},
    "Bomber":           {"elixir": 2, "roles": ["support","defense"], "tags": ["splash"]},
    "Musketeer":        {"elixir": 4, "roles": ["support","defense"], "tags": ["anti_air","ranged"]},
    "Baby Dragon":      {"elixir": 4, "roles": ["support","defense"], "tags": ["anti_air","splash","air_attacker"]},
    "Prince":           {"elixir": 5, "roles": ["offense","support"], "tags": ["ground_dps"]},
    "Wizard":           {"elixir": 5, "roles": ["support","defense"], "tags": ["splash","anti_air","ranged"]},
    "Mini P.E.K.K.A":   {"elixir": 4, "roles": ["support","defense"], "tags": ["tank_killer","ground_dps"]},
    "Spear Goblins":    {"elixir": 2, "roles": ["support","defense"], "tags": ["anti_air","ranged","swarm"]},
    "Giant Skeleton":   {"elixir": 6, "roles": ["support","defense"], "tags": ["splash","ground_dps"]},
    "Hog Rider":        {"elixir": 4, "roles": ["offense","wincon"], "tags": ["wincon","ground_dps"]},
    "Minion Horde":     {"elixir": 5, "roles": ["support","offense"], "tags": ["anti_air","air_attacker","swarm"]},
    "Ice Wizard":       {"elixir": 3, "roles": ["support","defense"], "tags": ["anti_air","control","ranged"]},
    "Royal Giant":      {"elixir": 6, "roles": ["offense","wincon"], "tags": ["wincon","ranged"]},
    "Guards":           {"elixir": 3, "roles": ["defense"],             "tags": ["swarm","ground_dps"]},
    "Princess":         {"elixir": 3, "roles": ["support","defense"], "tags": ["anti_air","splash","ranged"]},
    "Dark Prince":      {"elixir": 4, "roles": ["support","offense"], "tags": ["splash","ground_dps"]},
    "Three Musketeers": {"elixir": 9, "roles": ["support","offense"], "tags": ["anti_air","ranged"]},
    "Lava Hound":       {"elixir": 7, "roles": ["offense","wincon"], "tags": ["wincon","air_attacker"]},
    "Ice Spirit":       {"elixir": 1, "roles": ["cycle","support"],  "tags": ["cycle"]},
    "Fire Spirit":      {"elixir": 1, "roles": ["cycle","support"],  "tags": ["cycle","splash"]},
    "Miner":            {"elixir": 3, "roles": ["offense","wincon"], "tags": ["wincon","cycle","ground_dps"]},
    "Sparky":           {"elixir": 6, "roles": ["support","offense"], "tags": ["splash","ground_dps"]},
    "Bowler":           {"elixir": 5, "roles": ["support","defense"], "tags": ["splash","ground_dps"]},
    "Lumberjack":       {"elixir": 4, "roles": ["support","offense"], "tags": ["ground_dps","control"]},
    "Battle Ram":       {"elixir": 4, "roles": ["offense","wincon"], "tags": ["wincon"]},
    "Inferno Dragon":   {"elixir": 4, "roles": ["support","defense"], "tags": ["tank_killer","air_attacker"]},
    "Ice Golem":        {"elixir": 2, "roles": ["cycle","support"],  "tags": ["cycle","kite"]},
    "Mega Minion":      {"elixir": 3, "roles": ["support","defense"], "tags": ["anti_air","air_attacker"]},
    "Dart Goblin":      {"elixir": 3, "roles": ["support","defense"], "tags": ["anti_air","ranged"]},
    "Goblin Gang":      {"elixir": 3, "roles": ["defense"],             "tags": ["swarm","ground_dps","anti_air"]},
    "Electro Wizard":   {"elixir": 4, "roles": ["support","defense"], "tags": ["anti_air","control","ranged"]},
    "Elite Barbarians": {"elixir": 6, "roles": ["offense","support"], "tags": ["ground_dps"]},
    "Hunter":           {"elixir": 4, "roles": ["support","defense"], "tags": ["anti_air","tank_killer","ranged"]},
    "Executioner":      {"elixir": 5, "roles": ["support","defense"], "tags": ["splash","anti_air","ranged"]},
    "Bandit":           {"elixir": 3, "roles": ["offense","support"], "tags": ["ground_dps"]},
    "Royal Recruits":   {"elixir": 7, "roles": ["defense"],             "tags": ["swarm","ground_dps"]},
    "Night Witch":      {"elixir": 4, "roles": ["support","offense"], "tags": ["spawner"]},
    "Bats":             {"elixir": 2, "roles": ["support","defense"], "tags": ["anti_air","air_attacker","swarm"]},
    "Royal Ghost":      {"elixir": 3, "roles": ["support","offense"], "tags": ["ground_dps"]},
    "Ram Rider":        {"elixir": 5, "roles": ["offense","wincon"], "tags": ["wincon","control"]},
    "Zappies":          {"elixir": 4, "roles": ["support","defense"], "tags": ["control","anti_air","ranged"]},
    "Rascals":          {"elixir": 5, "roles": ["support","defense"], "tags": ["anti_air","ranged","swarm"]},
    "Cannon Cart":      {"elixir": 5, "roles": ["support","offense"], "tags": ["ranged"]},
    "Mega Knight":      {"elixir": 7, "roles": ["support","offense"], "tags": ["splash","ground_dps"]},
    "Skeleton Barrel":  {"elixir": 3, "roles": ["offense","support"], "tags": ["air_attacker","spawner","swarm"]},
    "Flying Machine":   {"elixir": 4, "roles": ["support","defense"], "tags": ["anti_air","air_attacker","ranged"]},
    "Wall Breakers":    {"elixir": 2, "roles": ["offense","support"], "tags": ["building_damage","cycle"]},
    "Royal Hogs":       {"elixir": 5, "roles": ["offense","wincon"], "tags": ["wincon","swarm","ground_dps"]},
    "Goblin Giant":     {"elixir": 6, "roles": ["offense","wincon"], "tags": ["wincon"]},
    "Fisherman":        {"elixir": 3, "roles": ["support","defense"], "tags": ["control","ground_dps"]},
    "Magic Archer":     {"elixir": 4, "roles": ["support","defense"], "tags": ["anti_air","ranged","pierce"]},
    "Electro Dragon":   {"elixir": 5, "roles": ["support","defense"], "tags": ["anti_air","splash","air_attacker","chain"]},
    "Firecracker":      {"elixir": 3, "roles": ["support","defense"], "tags": ["anti_air","ranged","splash"]},
    "Mighty Miner":     {"elixir": 4, "roles": ["offense","support"], "tags": ["ground_dps","control"]},
    "Elixir Golem":     {"elixir": 3, "roles": ["offense","support"], "tags": ["ground_dps"]},
    "Battle Healer":    {"elixir": 4, "roles": ["support","defense"], "tags": ["heal"]},
    "Skeleton King":    {"elixir": 4, "roles": ["offense","support"], "tags": ["spawner","swarm","ground_dps"]},
    "Mother Witch":     {"elixir": 4, "roles": ["support","defense"], "tags": ["control","spawner"]},
    "Electro Giant":    {"elixir": 7, "roles": ["offense","wincon"], "tags": ["wincon"]},
    "Phoenix":          {"elixir": 4, "roles": ["support","defense"], "tags": ["anti_air","air_attacker"]},
    "Electro Spirit":   {"elixir": 1, "roles": ["cycle","support"],  "tags": ["cycle","splash","control","anti_air"]},
    "Skeleton Dragons": {"elixir": 4, "roles": ["support","defense"], "tags": ["anti_air","splash","air_attacker"]},
    "Archer Queen":     {"elixir": 5, "roles": ["support","offense"], "tags": ["anti_air","ranged"]},
    "Golden Knight":    {"elixir": 4, "roles": ["support","offense"], "tags": ["ground_dps","control"]},
    "Monk":             {"elixir": 5, "roles": ["support","defense"], "tags": ["control"]},

    "Cannon":           {"elixir": 3, "roles": ["defense"],            "tags": ["building","tank_killer"]},
    "Goblin Hut":       {"elixir": 5, "roles": ["defense"],            "tags": ["building","spawner"]},
    "Mortar":           {"elixir": 4, "roles": ["offense","wincon"], "tags": ["wincon","building","ranged","splash"]},
    "Inferno Tower":    {"elixir": 5, "roles": ["defense"],            "tags": ["building","tank_killer"]},
    "Bomb Tower":       {"elixir": 4, "roles": ["defense"],            "tags": ["building","splash"]},
    "Barbarian Hut":    {"elixir": 6, "roles": ["defense"],            "tags": ["building","spawner"]},
    "Tesla":            {"elixir": 4, "roles": ["defense"],            "tags": ["building","anti_air"]},
    "Elixir Collector": {"elixir": 6, "roles": ["support"],            "tags": ["building","pump"]},
    "X-Bow":            {"elixir": 6, "roles": ["offense","wincon"], "tags": ["wincon","building","ranged"]},
    "Tombstone":        {"elixir": 3, "roles": ["defense"],            "tags": ["building","spawner"]},
    "Furnace":          {"elixir": 4, "roles": ["defense"],            "tags": ["building","spawner"]},
    "Goblin Cage":      {"elixir": 4, "roles": ["defense"],            "tags": ["building","tank_killer"]},
    "Goblin Drill":     {"elixir": 4, "roles": ["offense","wincon"], "tags": ["wincon","building","spawner"]},

    "Fireball":         {"elixir": 4, "roles": ["spell"],               "tags": ["medium_spell","splash"]},
    "Arrows":           {"elixir": 3, "roles": ["spell"],               "tags": ["small_spell","splash","anti_air"]},
    "Rage":             {"elixir": 2, "roles": ["spell"],               "tags": ["control"]},
    "Rocket":           {"elixir": 6, "roles": ["spell"],               "tags": ["big_spell"]},
    "Goblin Barrel":    {"elixir": 3, "roles": ["spell"],               "tags": ["wincon","spell_like"]},
    "Freeze":           {"elixir": 4, "roles": ["spell"],               "tags": ["control"]},
    "Mirror":           {"elixir": 1, "roles": ["spell"],               "tags": ["control"]},
    "Lightning":        {"elixir": 6, "roles": ["spell"],               "tags": ["big_spell"]},
    "Zap":              {"elixir": 2, "roles": ["spell"],               "tags": ["small_spell"]},
    "Poison":           {"elixir": 4, "roles": ["spell"],               "tags": ["medium_spell","splash"]},
    "Graveyard":        {"elixir": 5, "roles": ["spell"],               "tags": ["wincon","spell_like"]},
    "The Log":          {"elixir": 2, "roles": ["spell"],               "tags": ["small_spell","splash"]},
    "Tornado":          {"elixir": 3, "roles": ["spell"],               "tags": ["control","splash"]},
    "Clone":            {"elixir": 3, "roles": ["spell"],               "tags": ["control"]},
    "Earthquake":       {"elixir": 3, "roles": ["spell"],               "tags": ["medium_spell"]},
    "Barbarian Barrel": {"elixir": 2, "roles": ["spell"],               "tags": ["small_spell","splash"]},
    "Giant Snowball":   {"elixir": 2, "roles": ["spell"],               "tags": ["small_spell","splash","anti_air"]},
    "Royal Delivery":   {"elixir": 3, "roles": ["spell"],               "tags": ["small_spell","splash"]},

    "Heal Spirit":      {"elixir": 1, "roles": ["cycle","support"],  "tags": ["cycle","heal","splash"]},
}
